version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/api/Dockerfile
      target: prod
    image: rosatom_cluster_api:${ROSATOM_CLUSTER_API_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      redis:
        condition: service_healthy
      rmq:
        condition: service_healthy
    environment:
      ROSATOM_CLUSTER_API_HOST: 0.0.0.0
      ROSATOM_CLUSTER_API_RABBIT_HOST: rosatom_cluster_api-rmq
      ROSATOM_CLUSTER_API_REDIS_HOST: rosatom_cluster_api-redis
    healthcheck:
      test: curl --fail http://${ROSATOM_CLUSTER_API_HOST}:${ROSATOM_CLUSTER_API_PORT}/health || echo 1
      interval: 3s
      timeout: 3s
      retries: 50
    extra_hosts:
    - "host.docker.internal:host-gateway"

  worker:
    build:
      context: .
      dockerfile: ./deploy/worker/Dockerfile
    image: worker:latest
    restart: always
    depends_on:
      api:
        condition: service_healthy
      rmq:
        condition: service_healthy
    environment:
      ROSATOM_CLUSTER_API_HOST: 0.0.0.0
      ROSATOM_CLUSTER_API_RABBIT_HOST: forecast_api-rmq
    deploy:
      # Подобрать по нагрузке
      replicas: 1

  redis:
    image: bitnami/redis:6.2.5
    hostname: "rosatom_cluster_api-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  rmq:
    image: rabbitmq:3.9.16-alpine
    hostname: "rosatom_cluster_api-rmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics check_running -q
      interval: 3s
      timeout: 3s
      retries: 50
