version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    # - "8000:8000"
    - "9446:8000"
    build:
      target: dev
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      ROSATOM_CLUSTER_API_RELOAD: "True"

    rmq:
      ports:
        - "5672:5672"
