INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('AKKUYU NÜKLEER ANONİM ŞİRKETİ','АО АККУЮ НУКЛЕАР','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('TİTAN2 IC İÇTAŞ İNŞAAT A.Ş.','АО АККУЮ НУКЛЕАР','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('«Московский проектный институт» Московский филиал АО «Атомэнергопроект»','Атомэнергопроект','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('«Опытное конструкторское бюро машиностроения имени И. И. Африкантова»','Опытное конструкторское бюро машиностроения им. И. И. Африкантова','ОКБМ Африкантов',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АКЦИОНЕРНОЕ ОБЩЕСТВО КОНЦЕРН ТИТАН-2','Концерн Титан-2','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АКЦИОНЕРНОЕ ОБЩЕСТВО НАУЧНО-ИССЛЕДОВАТЕЛЬСКИЙ ИНСТИТУТ КОНСТРУКЦИОННЫХ МАТЕРИАЛОВ НА ОСНОВЕ ГРАФИТА НИИГРАФИТ','Научно-исследовательский институт конструкционных материалов на основе графита','НИИграфит',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО  Атомэнергопроект','Атомэнергопроект','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО  Ведущий Научно-Исследовательский Промышленный Институт промышленной технологии','Ведущий проектно-изыскательский и научно-исследовательский институт промышленной технологии','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ''ИНСТИТУТ РЕАКТОРНЫХ МАТЕРИАЛОВ''','Институт реакторных материалов','АО "ИРМ"',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО « КОНСИСТ-ОС»','Консист-Оператор-Связи','КОНСИСТ-ОС',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Атомтехэнерго» Московский филиал «Центратомтехэнерго»','Атомтехэнерго','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Атомэнергопроект»','Атомэнергопроект','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Атомэнергопроект» Санкт-Петербургский проектный институт ','Атомэнергопроект','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Высокотехнологичный научно-исследовательский институт неорганических материалов имени академика А.А. Бочвара»','Высокотехнологический  научно-исследовательский  институт неорганических материалов имени  академика А.А. Бочвара','ВНИИНМ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Государственный специализированный проектный институт»','Государственный специализированный проектный институт','ГСПИ',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Государственный специализированный проектный институт» ','Государственный специализированный проектный институт','ГСПИ',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Гринатом»','Гринатом','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Инжиниринговая компания «АЭМ-технологии»','Инжиниринговая компания «АЭМ-технологии»','«АЭМ-технологии»',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Концерн Росэнергоатом» Нововоронежская Атомная Станция','Нововоронежская Атомная Станция','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «НИКИМТ-Атомстрой»','НИКИМТ Атомстрой','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «ОКБМ АФРИКАНТОВ»','Опытное конструкторское бюро машиностроения им. И. И. Африкантова','ОКБМ Африкантова',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Объединённая теплоэнергетическая компания»','Объединённая теплоэнергетическая компания','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Русатом Оверсиз»','АО «Русатом Оверсиз»','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Русатом Оверсиз»','АО «Сибур-Химпром»','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «ФНПЦ «ПО «Старт» им. М.В.Проценко»','Старт, производственное объединение','ПО «Старт» им. М.В. Проценко',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «ФНПЦ «ПО «Старт» им. М.В.Проценко»','Центральный проектно-технологический институт','',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Цифровые платформы и решения Умного Города»','Цифровые платформы и решения Умного Города','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «Чепецкий механический завод»','Чепецкий механический завод','АО «ЧМЗ»',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО АККУЮ НУКЛЕАР','АО АККУЮ НУКЛЕАР','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО АСЭ','Атомстройэкспорт','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО АТОМЭНЕРГОПРОЕКТ','Атомэнергопроект','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО АТОМЭНЕРГОПРОЕКТ','Атомэнергопроект','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО АтомЭнергоСбыт','Атомэнергопроект','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Атомстройэкспорт','Атомстройэкспорт','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Атомэнергопроект','Атомэнергопроект','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Балаковоатомэнергоремонт','Балаковоатомэнергоремонт','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ВНИПИпромтехнологии','Всероссийский проектно-изыскательский научно-исследовательский институт промышленной технологии','ВНИПИПромтехнологии',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ВНИПИпротехнологии','Всероссийский проектно-изыскательский научно-исследовательский институт промышленной технологии','ВНИПИПромтехнологии',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ВПО Точмаш','Точмаш, Владимирское производственное объединение','ВПО «Точмаш»',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ВПО Точмаш - Центр ОКР','Точмаш, Владимирское производственное объединение','ВПО «Точмаш»',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Ведущий проектно-изыскательский и научно-исследовательский институт промышленной технологии','Ведущий проектно-изыскательский и научно-исследовательский институт промышленной технологии','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Владимирское производственное объединение Точмаш','Точмаш, Владимирское производственное объединение','ВПО «Точмаш»',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Высокотехнологический институт неорганических материалов им. ак.А.А.Бочвара»','Высокотехнологический  научно-исследовательский  институт неорганических материалов имени  академика А.А. Бочвара','ВНИИНМ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Высокотехнологический исследовательский институт неорганических материалов','Высокотехнологический  научно-исследовательский  институт неорганических материалов имени  академика А.А. Бочвара','ВНИИНМ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Высокотехнологический научно-исследовательский институт неорганических материалов имени академика А.А. Бочвара','Высокотехнологический  научно-исследовательский  институт неорганических материалов имени  академика А.А. Бочвара','ВНИИНМ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Государственный специализированный проектный институт','Государственный специализированный проектный институт','ГСПИ',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Гринатом','АО Гринатом','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Гринатом Отдел систем промышленной автоматизации','АО Гринатом','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Далур','АО Далур','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ЕВРАЗ ЗСМК','ЕВРАЗ ОБЪЕДИНЁННЫЙ ЗАПАДНО-СИБИРСКИЙ МЕТАЛЛУРГИЧЕСКИЙ Комбинат ','ЕВРАЗ ЗСМК',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ЕВРАЗ НТМК','ЕВРАЗ Нижнетагильский металлургический комбинат','АО ЕВРАЗ НТМК',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ЕВРАЗ НТМК ','ЕВРАЗ Нижнетагильский металлургический комбинат','АО ЕВРАЗ НТМК',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ЕВРАЗ ОБЪЕДИНЁННЫЙ ЗАПАДНО-СИБИРСКИЙ МЕТАЛЛУРГИЧЕСКИЙ Комбинат ','ЕВРАЗ ОБЪЕДИНЁННЫЙ ЗАПАДНО-СИБИРСКИЙ МЕТАЛЛУРГИЧЕСКИЙ Комбинат ','ЕВРАЗ ЗСМК',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ЕВРАЗ ОБЪЕДИНЕННЫЙ ЗАПАДНО-СИБИРСКИЙ МЕТАЛЛУРГИЧЕСКИЙ КОМБИНАТ','ЕВРАЗ ОБЪЕДИНЁННЫЙ ЗАПАДНО-СИБИРСКИЙ МЕТАЛЛУРГИЧЕСКИЙ Комбинат ','ЕВРАЗ ЗСМК',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ЕВРАЗ ОБЪЕДИНЕННЫЙ ЗАПАДНО-СИБИРСКИЙМЕТАЛЛУРГИЧЕСКИЙ КОМБИНАТ','ЕВРАЗ ОБЪЕДИНЁННЫЙ ЗАПАДНО-СИБИРСКИЙ МЕТАЛЛУРГИЧЕСКИЙ Комбинат ','ЕВРАЗ ЗСМК',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ЕВРАЗ ОБЪЕДИНЕННЫЙ ЗАПАДНО-СИБИРСКИЙМЕТАЛЛУРГИЧЕСКИЙ КОМБИНАТ','ЕВРАЗ ОБЪЕДИНЁННЫЙ ЗАПАДНО-СИБИРСКИЙ МЕТАЛЛУРГИЧЕСКИЙ Комбинат ','ЕВРАЗ ЗСМК',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Инжиниринговая компания «АСЭ» (АО ИК «АСЭ»)','АО Инжиниринговая компания АСЭ','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Инжиниринговая компания АСЭ','АО Инжиниринговая компания АСЭ','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Инжиниринговая компания АЭМ-технологии','АО Инжиниринговая компания АЭМ-технологии','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО КОНСИСТ-ОС','Консист-Оператор-Связи','КОНСИСТ-ОС',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО КОНСИСТ-ОС ','Консист-Оператор-Связи','КОНСИСТ-ОС',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО КОНЦЕРН ТИТАН-2','Концерн Титан-2','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Консист-ОС','Консист-Оператор-Связи','КОНСИСТ-ОС',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Консист-Оператор связи','Консист-Оператор-Связи','КОНСИСТ-ОС',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Консист-Оператор-Связи','Консист-Оператор-Связи','КОНСИСТ-ОС',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Концерн Росэнергоатом Балаковская АЭС','Балаковская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Концерн Росэнергоатом Ростовская атомная станция','Ростовская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Концерн Росэнергоатом филиал Нововоронежская АЭС','Нововоронежская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Концерн Росэнергоатом, филиал Курская атомная станция, Управление капитального строительства Курской АЭС-2','Курская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Концерн ТИТАН-2','Концерн Титан-2','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Концерн Титан-2','Концерн Титан-2','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Концерн Титан-2 отдел строительного контроля','Концерн Титан-2','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО МСЗ','Машиностроительный завод','МСЗ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО МСЗ г.Электросталь ','Машиностроительный завод','МСЗ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Машиностроительный завод','Машиностроительный завод','МСЗ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Научный и Конструкторский Институт Монтажной Технологии-Атомстрой','АО Научный и Конструкторский Институт Монтажной Технологии-Атомстрой','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Нижегородская инжиниринговая компания Атомэнергопроект (АО НИАЭП)','Атомэнергопроект','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Никимт атомстрой','НИКИМТ Атомстрой','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ОКБМ АФРИКАНТОВА ','Опытное конструкторское бюро машиностроения им. И. И. Африкантова','ОКБМ Африкантова',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ОКБМ Африкантов','Опытное конструкторское бюро машиностроения им. И. И. Африкантова','ОКБМ Африкантова',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Опытное Конструкторское Бюро Машиностроения им. Африкантова','Опытное конструкторское бюро машиностроения им. И. И. Африкантова','ОКБМ Африкантова',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Опытное Конструкторское Бюро Машиностроения имени И.И. Африкантова','Опытное конструкторское бюро машиностроения им. И. И. Африкантова','ОКБМ Африкантова',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Ордена Трудового Красного Знамени и ордена труда ЧССР - опытное конструкторское бюро ГИДРОПРЕСС','Гидропресс, Опытное конструкторское бюро','Гидропресс',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО РИР филиал в г. Озерске','АО РИР филиал в г. Озерске','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО СХК ЦГЭС','АО СХК ЦГЭС','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Сибирский химический комбинат','Сибирский химический комбинат','СХК',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО УЭХК','Уральский электрохимический комбинат','',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Уральский электрохимический комбинат','Уральский электрохимический комбинат','',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ФНПЦ ПО СТАРТ им. М.В. Проценко','Старт, производственное объединение','ПО «Старт» им. М.В. Проценко',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ФЦНИВТ СНПО ЭЛЕРОН','Элерон, Специальное научно-производственное объединение','«ФЦНИВТ СНПО «Элерон»',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ФЦНИВТ СНПО Элерон','Элерон, Специальное научно-производственное объединение','«ФЦНИВТ СНПО «Элерон»',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Хиагда','Хиагда','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ЦКБМ','Центральное конструкторское бюро машиностроения','ЦКБМ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ЦПТИ','Центральный проектно-технологический институт','ЦПТИ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ЦПТИ, Уральский филиал, научно-исследовательский и опытно-конструкторский отдел','Центральный проектно-технологический институт','ЦПТИ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Центральное конструкторское бюро машиностроения','Центральное конструкторское бюро машиностроения','ЦКБМ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Центральный проектно-технологический институт','Центральный проектно-технологический институт','ЦПТИ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Цифровые платформы и решения Умного города','Цифровые платформы и решения Умного Города','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Цифровые платформы и решения умного города','Цифровые платформы и решения Умного Города','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО ЧМЗ','Чепецкий механический завод','АО «ЧМЗ»',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Чепецкий Механический Завод','Чепецкий механический завод','АО «ЧМЗ»',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Чепецкий механический завод','Чепецкий механический завод','АО «ЧМЗ»',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Электрогорский научно-исследовательский центр по безопасности атомных электростанций','Электрогорский научно-исследовательский центр по безопасности атомных электростанций','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО Энергоспецмонтаж ','Энергоспецмонтаж','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО инжиноринговая компания АЭМ-технологии Петрозаводскмаш','АО Инжиниринговая компания АЭМ-технологии','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО концерн титан-2','Концерн Титан-2','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО по наладке','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО филиал концерна Росэнеогоатом  калининская АЭС','Калининская АЭС','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО “Сибирский химический комбинат“','Сибирский химический комбинат','СХК',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «АТОМПРОЕКТ»','Научно-исследовательский и проектно-конструкторский институт энергетических технологий «АТОМПРОЕКТ»','«АТОМПРОЕКТ»',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АО «АТОМПРОЕКТ»','Научно-исследовательский и проектно-конструкторский институт энергетических технологий «АТОМПРОЕКТ»','«АТОМПРОЕКТ»',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('АОНИКИМТ-АТОМСТРОЙ Дирекция на Курской АЭС','НИКИМТ Атомстрой','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное Общество Гринатом','АО Гринатом','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное Общество Далматовский Уран','Далматовский Уран','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное Общество Институт Реакторных Материалов','Институт реакторных материалов','АО "ИРМ"',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное Общество Машиностроительный завод','Машиностроительный завод','',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное Общество Федеральный Научно-Производственный Центр Производственное Объединение СТАРТ им .М.В.Проценко','Старт, производственное объединение','ПО «Старт» им. М.В. Проценко',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество  Научно-исследовательский институт Научно-производственное объединение ЛУЧ','Луч, Научно-исследовательский институт — Научно-производственное объединение','НИИ НПО «Луч»',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество «Атомспецтранс»','Атомспецтранс','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество «Ведущий проектно-изыскательский и научно-исследовательский институт промышленной технологии».','Ведущий проектно-изыскательский и научно-исследовательский институт промышленной технологии','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество «КОНЦЕРН ТИТАН-2»','Концерн Титан-2','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество «Концерн Титан 2»','Концерн Титан-2','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество «Производственное объединение «Электрохимический завод»','Производственное объединение «Электрохимический завод','ЭХЗ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество «Русатом Автоматизированные системы управления»','Русатом автоматизированные системы управления','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество «Русатом Инфраструктурные решения»','Русатом Инфраструктурные решения','РИР',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество «Федеральный научно-производственный центр «Производственное объединение «Старт» имени М.В.Проценко»','Старт, производственное объединение','ПО «Старт» им. М.В. Проценко',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество «Центральный проектно-технологический институт»','Центральный проектно-технологический институт','ЦПТИ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Ангарский электролизный химический комбинат','Ангарский электролизный химический комбинат','АЭХК',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество АтомЭнергоСбыт','АтомЭнергоСбыт','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Атомспецтранс Озерский филиал','Атомспецтранс','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Атомстройэкспорт','Атомстройэкспорт','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Атомтрубопроводмонтаж','Атомтрубопроводмонтаж','',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Атомтрубопроводмонтаж ','Атомтрубопроводмонтаж','',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Атомэнергопроект','Атомэнергопроект','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Атомэнергосбыт','АтомЭнергоСбыт','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Ведущий проектно-изыскательский и научно-исследовательский институт промышленной технологии','Ведущий проектно-изыскательский и научно-исследовательский институт промышленной технологии','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Высокотехнологический научно-исследовательский институт институт неорганических материалов им.А.А.','Высокотехнологический  научно-исследовательский  институт неорганических материалов имени  академика А.А. Бочвара','ВНИИНМ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Высокотехнологический научно-исследовательский институт неорганических материалов имени академика А.А. Бочвара','Высокотехнологический  научно-исследовательский  институт неорганических материалов имени  академика А.А. Бочвара','ВНИИНМ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Государственный научный центр Российской Федерации Троицкий институт инновационных и термоядерных исследований','','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Государственный специализированный проектный институт обособленное подразделение в г Иркутске','Государственный специализированный проектный институт','ГСПИ',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Гринатом','АО Гринатом','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Далур','АО Далур','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Инжиниринговая компания АСЭ','АО Инжиниринговая компания АСЭ','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Институт реакторных  материалов','Институт реакторных материалов','АО "ИРМ"',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Институт реакторных материалов','Институт реакторных материалов','АО "ИРМ"',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Красноярский филиал Государственный специализированный проектный институт','Государственный специализированный проектный институт','ГСПИ',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Машиностроительный завод','Машиностроительный завод','МСЗ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Научно-исследовательский институт Научно-производственное объединение ЛУЧ','Луч, Научно-исследовательский институт — Научно-производственное объединение','НИИ НПО «Луч»',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Научный исследовательский институт научное производственное объединение Луч','Луч, Научно-исследовательский институт — Научно-производственное объединение','НИИ НПО «Луч»',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Опытное Конструкторское Бюро Машиностроения имени И.И. Африкантова','Опытное конструкторское бюро машиностроения им. И. И. Африкантова','ОКБМ Африкантова',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Опытное конструкторское бюро машиностроения имени И.И. Африкантова','Опытное конструкторское бюро машиностроения им. И. И. Африкантова','ОКБМ Африкантова',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Производственное объединение Электрохимический завод','Производственное объединение «Электрохимический завод','ЭХЗ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество РУСБУРМАШ','РУСБУРМАШ','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Русатом автоматизированные системы управления','Русатом автоматизированные системы управления','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Русатом инфраструктурные решения филиал в г. Глазове','Русатом Инфраструктурные решения','РИР',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Сибирский Химический Комбинат','Сибирский химический комбинат','СХК',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Сибирский химический комбинат','Сибирский химический комбинат','СХК',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Специализированный научно-исследовательский институт приборостроения','Специализированный научно-исследовательский институт приборостроения','СНИИП',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Федеральный научно-производственный центр Производственное объединениеСтарт имени М. В. Проценко','Старт, производственное объединение','ПО «Старт» им. М.В. Проценко',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Хиагда','Хиагда','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Центральное Конструкторское Бюро Машиностроения ','Центральное конструкторское бюро машиностроения','ЦКБМ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Центральное конструкторское бюро машиностроения','Центральное конструкторское бюро машиностроения','ЦКБМ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Цифровые платформы и решения умного города','Цифровые платформы и решения Умного Города','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Чепецкий Механический завод','Чепецкий механический завод','АО «ЧМЗ»',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество Чепецкий механический завод','Чепецкий механический завод','АО «ЧМЗ»',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Акционерное общество опытное конструкторское бюро машиностроения им. И. И. Африкантова','Опытное конструкторское бюро машиностроения им. И. И. Африкантова','ОКБМ Африкантова',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Артем Александрович Бондаренко','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Артем Резников','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Атомстройэкспорт','Атомстройэкспорт','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Аэм технологии Атоммаш','АО Инжиниринговая компания АЭМ-технологии','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Аэрокосмический колледж СибГУ им. М.Ф. Решетнева','Аэрокосмический колледж СибГУ им. М.Ф. Решетнева','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('БИТИ НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Балаково АтомЭнергоРемонт ','Балаковоатомэнергоремонт','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Балаковоатомэнергоремонт','Балаковоатомэнергоремонт','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Балаковоатомэнергоремонт - филиал АО Атомэнергоремонт','Балаковоатомэнергоремонт','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Балаковоатомэнергоремонт-филиал АО Атомэнергоремонт','Балаковоатомэнергоремонт','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Балаковская атомная электростанция','Балаковская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Балоковский инженерно технологический институт','Балоковский инженерно технологический институт','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ВИТИ НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ВПО Точмаш','Точмаш, Владимирское производственное объединение','ВПО «Точмаш»',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Ведущий инженер по ремонту электрического цеха участка по ремонту генераторов, электродвигателей 6 и 0.4 кВ','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Ведущий научно-исследовательский проектно-изыскательский институт промышленной технологии','Ведущий проектно-изыскательский и научно-исследовательский институт промышленной технологии','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Ведущий проектно-изыскательский и научно-исследовательский инсти','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Ведущий проектно-изыскательский и научно-исследовательский институт промышленной технологии','Ведущий проектно-изыскательский и научно-исследовательский институт промышленной технологии','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Волгодонский филиал Акционерного общества «Инжиниринговая компания ','АО Инжиниринговая компания АСЭ','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ГАПОУ СО УРТК им. А.С. Попова','ГАПОУ СО УРТК им. А.С. Попова','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ГБПОУ МГОК','notser','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Газпромнефть ИТО','Газпромнефть ИТО','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Горно Химический Комбинат','Горно-химический комбинат','ГХК',7);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Государственное бюджетное профессиональное образовательное учреждение ''Озерский технический колледж''','Озерский технический колледж','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Государственный университет аэрокосмического приборостроения','Государственный университет аэрокосмического приборостроения','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ДАЛУР','АО Далур','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Департамент информационных технологий ГХК','Горно-химический комбинат','ГХК',7);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Департамент капитального строительства','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Департамент капитального строительства отдел генплана, изысканий и землеустройства','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Дирекция по поддержке производства , подземный рудник 1','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Завод 156','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Завод 23 цех промышленного водоснабжения','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ИВТЭ НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Иатэ НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Институт Атомной Энергетики Национальный Исследовательский Ядерный Университет «МИФИ»','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Институт Атомной Энергетики Национальный Исследовательский Ядерный Университет Московский Инженерно Физический Институт','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Институт компьютерных технологий и информационной безопасности при Южном Федеральном Университете','Институт компьютерных технологий и информационной безопасности при Южном Федеральном Университете','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Институт теоретической и математической физики','Институт теоретической и математической физики','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Казанский (Приволжский) федеральный университет','Казанский (Приволжский) федеральный университет','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Калининатомэнергоремонт - филиал АО Атомэнергоремонт','Атомэнергоремонт','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Калининский филиал Калининатомтехэнерго АО Атомтехэнерго','Атомтехэнерго Калининский филиал «Центратомтехэнерго»','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Калининском Атомная Электростанция','Калининская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Кольская АЭС','Кольская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Комбинат «Электрохимприбор»','Электрохимприбор, комбинат','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Константин Попинов','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Конструкторское бюро 1','Центральное конструкторское бюро машиностроения','ЦКБМ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Лениградска атомная станция (Лениградская АЭС)','Лениградская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Ленинградская атомная электростанция','Лениградская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('МОПК НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Машиностроительный завод','Машиностроительный завод','',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Машиностроительный завод «ЗиО-Подольск»','Машиностроительный завод «ЗиО-Подольск»','',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Московский колледж архитектуры и градостроительства','Московский колледж архитектуры и градостроительства','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('НАУЧНО-ИССЛЕДОВАТЕЛЬСКИЙ ИНСТИТУТ КОНСТРУКЦИОННЫХ МАТЕРИАЛОВ НА ОСНОВЕ ГРАФИТА НИИГРАФИТ','Научно-исследовательский институт конструкционных материалов на основе графита','НИИграфит',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ЯДЕРНЫЙ УНИВЕРСИТЕТ «МИФИ» ОБНИНСКИЙ ИНСТИТУТ АТОМНОЙ ЭНЕРГЕТИКИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ЯДЕРНЫЙ УНИВЕРСИТЕТ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('НВПК НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Научно-исследовательский центр','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Национа́льный иссле́довательский я́дерный университет «МИФИ́» (Московский инженерно-физический институт)','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Национальный Исследовательский Томский Государственный университет','Национальный Исследовательский Томский Государственный университет','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Национальный исследовательский ядерный университет «МИФИ»','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Национальный исследовательский ядерный университет МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Нет','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Никимт атомстрой','НИКИМТ Атомстрой','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Никимт атомстрой ','НИКИМТ Атомстрой','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Новосибирский завод химконцентратов','Новосибирский завод химконцентратов','НЗХК',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Новосибирский национально исследовательский государственный университет','Новосибирский завод химконцентратов','',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ОАО «Российские железные дороги» Тюменская дистанция гражданских','Тюменская дистанция гражданских','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ОАО РЖД дистанция гражданских сооружений ','Тюменская дистанция гражданских','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ОАО Российский концерн по производству электрической и тепловой энергии на атомных станциях Росэнергоатом','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ОАО ФНПЦ ПО Старт','Старт, производственное объединение','ПО «Старт» им. М.В. Проценко',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ОБНИНСКИЙ ИНСТИТУТ АТОМНОЙ ЭНЕРГЕТИКИ НАЦИОНАЛЬНЫЙ ИССЛЕДОВАТЕЛЬСКИЙ ЯДЕРНЫЙ УНИВЕРСИТЕТ «МИФИ»','НИЯУ МИФИ','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ОБПОУ Курский монтажный техникум','ОБПОУ Курский монтажный техникум','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ РУСАТОМ-АДДИТИВНЫЕ ТЕХНОЛОГИИ','Русатом-Аддитивные технологии','',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ОКБМ АФРИКАНТОВ ','Опытное конструкторское бюро машиностроения им. И. И. Африкантова','ОКБМ Африкантова',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО «Додо Инжиниринг»','ООО «Додо Инжиниринг»','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО «НИИАР-ГЕНЕРАЦИЯ»','ООО «НИИАР-ГЕНЕРАЦИЯ»','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО «НИИАР-ГЕНЕРАЦИЯ»','ООО «НИИАР-ГЕНЕРАЦИЯ»','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО «Русатом инфраструктурные решения»','Русатом Инфраструктурные решения','РИР',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО АЛЬСТОМ Атомэнергомаш','ООО АЛЬСТОМ Атомэнергомаш','',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО Атоммаш-Сервис','ООО Атоммаш-Сервис','',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО Газпромнефть - Цифровые решения','ООО Газпромнефть - Цифровые решения','',12);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО Газпромнефть ИТО','Газпромнефть ИТО','',12);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО Газпромнефть-ЦР','ООО Газпромнефть-ЦР','',12);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО Газпромнефть-Цифровые решения','ООО Газпромнефть - Цифровые решения','',12);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО ЗапСибНефтехим','Сибирский химический комбинат','СХК',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО Калининская АЭС-сервис','Калининская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО Курская АЭС-Сервис','Курская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО НПО  Центротех','ООО НПО  Центротех','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО НПО Центротех','ООО НПО  Центротех','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО НПОЦентротех','ООО НПО  Центротех','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО Трест Рос Спец Энерго монтаж','ООО Трест Рос Спец Энерго монтаж','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ООО Энергоремонт','ООО Энергоремонт','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Обнинский институт атомной энергетики','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Обнинский институт ядерной физики НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Обособленное подразделение Томского филиала АО ГСПИ','Обособленное подразделение Томского филиала АО ГСПИ','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Общество с ограниченной ответственностью «Производственное ремонтно-эксплуатационное хозяйство Горно-химического комбина','Общество с ограниченной ответственностью «Производственное ремонтно-эксплуатационное хозяйство Горно-химического комбина','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Общество с ограниченной ответственностью Белоярская АЭС –Авто','Белоярская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Общество с ограниченной ответственностью Западно-сибирский нефтехимический комбинат','Сибирский химический комбинат','СХК',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Общество с ограниченной ответственностью Турбинные технологии ААЭМ','Общество с ограниченной ответственностью Турбинные технологии ААЭМ','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ОзТК','Озерский технический колледж','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Озерский технический колледж','Озерский технический колледж','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Озерский технический колледж ','Озерский технический колледж','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Озерский технологический институт - филиал Нияу мифи','Озерский технический колледж','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Озёрский Технический Колледж','Озерский технический колледж','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Озёрский технический колледж','Озерский технический колледж','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Озёрский филиал АО  Атомспецтранс.','Атомспецтранс','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Ордена Трудового Красного Знамени ФГБОУ ВО «Московский технический университет связи и информатики»','Ордена Трудового Красного Знамени ФГБОУ ВО «Московский технический университет связи и информатики»','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Отдел капитального строительства группа','Отдел капитального строительства группа','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Отдел развития производственной системы «Росатом»','Отдел развития производственной системы «Росатом»','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Отдел разработки вспомогательного оборудования ГЦ, ООО НПО Центротех','ООО НПО  Центротех','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Отдел технического контроля','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ПАО Ковровский механический завод','Ковровский механический завод','',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ПАО Корпорация Иркут в г. Воронеже','Корпорация Иркут','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ПАО Машиностроительный завод','Машиностроительный завод','МСЗ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ПАО Машиностроительный завод ЗиО Подольск','Машиностроительный завод','МСЗ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ПАО Нижнекамскнефтехим','Нижнекамскнефтехим','',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ПАО ППГХО Объединенное автохозяйство','Приаргунское производственное горно-химическое объединение','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ПАО Приаргунское производственное горно-химическое объединение','Приаргунское производственное горно-химическое объединение','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ПАО'' ППГХО''  '' ОАХ''','Приаргунское производственное горно-химическое объединение','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ПО Маяк','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ПетрозаводскМаш','Литейный завод «Петрозаводскмаш»','',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Подразделение Multi-D','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Приборно-механический завод, цех КДСЕ','Приборно-механический завод, цех КДСЕ','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Приборостроительный завод','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Производственное обьединение Маяк, Реакторный завод','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Публичное акционерное общество «Новосибирский завод химконцентратов»','Новосибирский завод химконцентратов','НЗХК',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Публичное акционерное общество Новосибирский завод химконцентратов','Новосибирский завод химконцентратов','НЗХК',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Публичное акционерное общество Приаргунское производственное горно-химическое объединение','Приаргунское производственное горно-химическое объединение','',8);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('РФЯЦ ВНИИЭФ','Всероссийский научно-исследовательский институт экспериментальной физики, Российский федеральный ядерный центр','РФЯЦ-ВНИИЭФ',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Ремонтно-строительно-монтажный цех 097','Ремонтно-строительно-монтажный цех 097','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Росатом','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Ростовская АЭС','Ростовская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Русатом Инфраструктурные решения','Русатом Инфраструктурные решения','РИР',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('СГТ 037','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Санкт-Петербургский Государственный Университет','Санкт-Петербургский Государственный Университет Аэрокосмического Приборостроения','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Санкт-Петербургский Государственный Университет Аэрокосмического Приборостроения','Санкт-Петербургский Государственный Университет Аэрокосмического Приборостроения','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Санкт-Петербургский государственный университет аэрокосмического приборостроения ','Санкт-Петербургский Государственный Университет Аэрокосмического Приборостроения','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Санкт-Петербургский филиал АО «ФЦНИВТ «СНПО «Элерон» - «ВНИПИЭТ»','Элерон, Специальное научно-производственное объединение','АО ФЦНИВТ СНПО ЭЛЕРОН',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Северский технологический институт','Северский технологический институт','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Служба главного технолога','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Служба промышленной безопасности','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Служба управления проектами','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Служба хранения транспортирования и контроля спецпродукции','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Служба экологии, цех хранения радиоактивных отходов и ликвидации радиоактивных загрязнений','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Сметно-договорной отдел УКС','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Снежинкий физико-технический институт НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Снежинский физико-технический институт','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Снежинский физико-технический институт Национального исследовательского ядерного университета МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Специализированный научно исследовательский институт приборостроения','Специализированный научно-исследовательский институт приборостроения','СНИИП',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Специализированный научно-исследовательский институт приборостроения','Специализированный научно-исследовательский институт приборостроения','СНИИП',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Студент','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ТИ НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ТТИ НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Татьяна Олеговна Вербицкая','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Технологический Институт Национальный Исследовательский Ядерный Университет МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Технологический Институт Национальный исследовательский ядерный университет МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Титан 2','Концерн Титан-2','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Трест Рос Спец Энерго Монтаж','Концерн Титан-2','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Трестросспецэлектромонтаж','Трестросспецэлектромонтаж','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Трехгорный технологический институт НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Трехгорный технологический университет филиал НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Трёхгорный Технологический Институт Национальный Исследовательский Ядерный Университет МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Тюменская дистанция гражданских сооружений','Тюменская дистанция гражданских','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('УФ АО СНПО ЭлеронУПИИ ВНИПИЭТ','ВНИПИЭТ','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('УФ АО ФЦНИВТ СНПО Элерон УПИИ ВНИПИЭТ','ВНИПИЭТ','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Управление Капитального Строительства','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Управление автомобильного транспорта','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Управление предприятия','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Управление проектной продукции по качеству г Нижний Новгород АО Атомэнергопроект ','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Управления по техническому контролю при изготовлении оборудования для АЭС Российской Федерации','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('УрТК НИЯУ МИФИ','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Уральский технологический колледж - филиал НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Уральский технологический колледж филиал НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Уральский технологический колледж, филиал НИЯУ МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Уральский филиал АО ЦПТИ','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Уральский электрохимический комбинат','Уральский электрохимический комбинат','',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГАОУ ВО «Национальный исследовательский ядерный университет «МИФИ»','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГБОУ ВО Алтайский государственный университет','Алтайский государственный университет','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГБОУ ВО НИУ МЭИ','НИУ МЭИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП «ПО «Маяк»','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП «Приборостроительный завод им. К.А. Володина»','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП «Приборостроительный завод имени К.А. Володина»','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ВНИИА','Всероссийский научно-исследовательский институт автоматики им. Н.Л. Духова','ВНИИА им. Н.Л. Духова',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Всероссийский научно-исследовательский институт автоматики им. Н.Л. Духова','Всероссийский научно-исследовательский институт автоматики им. Н.Л. Духова','ВНИИА им. Н.Л. Духова',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Горно-химический комбинат','Горно-химический комбинат','ГХК',7);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Комбинат Электрохимприбор','Электрохимприбор, комбинат','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП КомбинатЭлектрохимприбор','Электрохимприбор, комбинат','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Маяк','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП НИТИ им. А. П. Александрова','Научно-исследовательский технологический институт им. А. П. Александрова','НИТИ',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП НИТИ им. А.П. Александрова','Научно-исследовательский технологический институт им. А. П. Александрова','НИТИ',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Национальный оператор по обращению с радиоактивными отходами','Национальный оператор по обращению с радиоактивными отходами','НО РАО',7);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ОБЪЕДИНЕННЫЙ ЭКОЛОГО-ТЕХНОЛОГИЧЕСКИЙ И НАУЧНО-ИССЛЕДОВАТЕЛЬСКИЙ ЦЕНТР ПО ОБЕЗВРЕЖИВАНИЮ РАО И ОХРАНЕ ОКРУЖАЮЩЕЙ СР','','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ПО «Маяк»','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ПО МАЯК','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ПО МАЯК ПМЗ ЦИНО','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ПО МАЯК, завод 235','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ПО Маяк','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ПО Маяк Центральная заводская лаборатория ','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ПО Маяк, радиохимический завод','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ПОМАЯК','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ПОМаяк','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ПСЗ','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Предприятие по обращению с радиоактивными отходами РосРАО','Предприятие по обращению с радиоактивными отходами «РосРАО»','',7);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Приборостроительный завод','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Приборостроительный завод им. К.А. Володина','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Производственное объединение Маяк','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП РФЯЦ ВНИИЭФ','Всероссийский научно-исследовательский институт экспериментальной физики, Российский федеральный ядерный центр','РФЯЦ-ВНИИЭФ',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП РФЯЦ-ВНИИТФ им. академ. Е.И. Забабахина','Всероссийский научно-исследовательский институт экспериментальной физики, Российский федеральный ядерный центр','РФЯЦ-ВНИИЭФ',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП РФЯЦ-ВНИИЭФ','Всероссийский научно-исследовательский институт экспериментальной физики, Российский федеральный ядерный центр','РФЯЦ-ВНИИЭФ',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП РФЯЦ-ВНИИЭФ - филиал НИИИС им. Ю.Е.Седакова','Всероссийский научно-исследовательский институт экспериментальной физики, Российский федеральный ядерный центр','РФЯЦ-ВНИИЭФ',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Российский Федеральный Ядерный Центр - Всероссийский научно-исследовательский институт технической физики имени академика Е.И. Забабахина','Всероссийский научно-исследовательский институт экспериментальной физики, Российский федеральный ядерный центр','РФЯЦ-ВНИИЭФ',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Российский федеральный ядерный центр–Всероссийский научно- исследовательский институт экспериментальной физики (ФГУП РФЯЦ-ВНИИЭФ)','Всероссийский научно-исследовательский институт экспериментальной физики, Российский федеральный ядерный центр','РФЯЦ-ВНИИЭФ',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Российский федеральный ядерный центр–Всероссийский научно- исследовательский институт экспериментальной физики Государственной корпорации по атомной энергии Росатом','','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП Электрохимприбор','Электрохимприбор, комбинат','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП ЭлетроХимПрибор','Электрохимприбор, комбинат','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУП комбинат электрохимприбор','Электрохимприбор, комбинат','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУПКомбинат Электрохимприбор','Электрохимприбор, комбинат','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУПКомбинатЭлектрохимприбор','Электрохимприбор, комбинат','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФГУПРадон','Электрохимприбор, комбинат','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ УНИТАРНОЕ ПРЕДПРИЯТИЕ «ГОРНО-ХИМИЧЕСКИЙ КОМБИНАТ»','Горно-химический комбинат','ГХК',7);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФЕДЕРАЛЬНОЕ ГОСУДАРСТВЕННОЕ УНИТАРНОЕ ПРЕДПРИЯТИЕ ПРИБОРОСТРОИТ','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА КОНСИСТ - ОПЕРАТОР СВЯЗИ БЕЛОЯРСКИЙ','Консист-Оператор-Связи Белоярский','КОНСИСТ-ОС Белоярский',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Фгуп Внииа им. Духова','Всероссийский научно-исследовательский институт автоматики им. Н.Л. Духова','ВНИИА им. Н.Л. Духова',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Фгуп по маяк','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('ФгупПСЗ имени К. А. Володина','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное Государственное Производственное объединение Маяк','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное Государственное Унитарное Предприятие  Приборостроительный Завод','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное Государственное Унитарное Предприятие «Комбинат «Электрохимприбор»','Электрохимприбор, комбинат','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное Государственное Унитарное Предприятие «Приборостроительный завод имени К.А.Володина»','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное Государственное Унитарное Предприятие «Производственное Объединение «МАЯК»','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное Государственное Унитарное Предприятие Приборо Строительный Завод','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное Государственное Унитарное Предприятие Приборостроительный завод имени К.А.Володина','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное автономное образовательное учреждение высшего образования «Санкт-Петербургский государственн','Санкт-Петербургский Государственный Университет Аэрокосмического Приборостроения','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное автономное образовательное учреждение высшего образования «Санкт-Петербургский государственный университет аэрокосмического приборостроения»','','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное бюджетное образовательное учреждение высшего образования «Национальный исследовательский уни','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное бюджетное образовательное учреждение высшего образования Национальный исследовательский уни','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное предприятие Национальный оператор по обращению с радиоактивными отходами','Национальный оператор по обращению с радиоактивными отходами','"НО РАО"',7);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие « Горно химический комбинат»','Горно-химический комбинат','ГХК',7);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие «Всероссийский научно-исследовательский институт автоматики им.Духова','Всероссийский научно-исследовательский институт автоматики им. Н.Л. Духова','ВНИИА им. Н.Л. Духова',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие «Производственное объединение «Маяк»','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие «Производственное объединение «Маяк», завод 235, цех 5','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие «Производственное объединение «Маяк», служба информационных технологий','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие «Федеральный экологический оператор»','Федеральный экологический оператор','ФГУП',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие «производственное объединение «Маяк»','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие Всероссийский научно-исследовательский институт автоматики им. Н.Л. Д','Всероссийский научно-исследовательский институт автоматики им. Н.Л. Духова','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие Горно-химический комбинат','Горно-химический комбинат','ГХК',7);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие НАЦИОНАЛЬНЫЙ ОПЕРАТОР ПО ОБРАЩЕНИЮ С РАДИОАКТИВНЫМИ ОТХОДАМИ','Национальный оператор по обращению с радиоактивными отходами','"НО РАО"',7);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие Научно-исследовательский институт Научно-производственное объединение «Луч»','Луч, Научно-исследовательский институт — Научно-производственное объединение','НИИ НПО «Луч»',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие Приборостроительный завод','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие Приборостроительный завод имени К.А. Володина','Приборостроительный завод имени К.А. Володина','ФГУП «ПСЗ»',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие Производственное объединение  Маяк','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие Производственное объединение Маяк','ПО «Маяк»','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Федеральное государственное унитарное предприятие горно химический комбинат','Горно-химический комбинат','ГХК',7);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал  акционерного общества  «Научно-исследовательский и конструкторский институт монтажной технологии – Атомстрой»  Обнинский инженерный центр НИКИМТ','НИКИМТ Атомстрой','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО ''АЭМ-технологии'' ''Атоммаш'' в г. Волгодонск','АО Инжиниринговая компания АЭМ-технологии','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО ''Концерн Росэнергоатом'' ''Балаковская атомная станция''','Балаковская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО ''Концерн Росэнергоатом'' ''Белоярская атомная станция''','Белоярская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО ''Концерн Росэнергоатом'' ''Калининская атомная станция''','Калининская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО ''Концерн Росэнергоатом'' ''Кольская атомная станция''','Кольская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО ''Концерн Росэнергоатом'' ''Курская атомная станция''','Нововороженская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО ''Концерн Росэнергоатом'' ''Нововоронежская атомная станция''','Нововоронежская Атомная Станция','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО ''Концерн Росэнергоатом'' ''Смоленская атомная станция''','Смоленская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО «Концерн Росэнергоатом» «Калининская атомная станция»','Калининская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО «Концерн Росэнергоатом» «Кольская атомная станция»','Кольская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО «Концерн Росэнергоатом» «Опытно-демонстрационный инженерный центр по выводу из эксплуатации»','Опытно-демонстрационный инженерный центр','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО АЭМ-технологии Петрозаводскмаш в г. Петрозаводск','АО Инжиниринговая компания АЭМ-технологии','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО АЭМ-технологии Петрозаводскмаш в г. Петрозаводск ','АО Инжиниринговая компания АЭМ-технологии','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО КОНСИСТ-ОС Кольский','Консист-Оператор-Связи','КОНСИСТ-ОС',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО КОНЦЕРН РОСЭНЕРГОАТОМРОСТОВСКАЯ АТОМНАЯ СТАНЦИЯ','Ростовская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО Концерн Росэнергоатом Балаковская атомная станция','Балаковская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО Концерн Росэнергоатом Белоярская АЭС','Белоярская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО Концерн Росэнергоатом Белоярская атомная станция','Белоярская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО Концерн Росэнергоатом Калининская атомная станция','Калининская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО Концерн Росэнергоатом Курская атомная станция','Курская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО Концерн Росэнергоатом Ленинградская АЭС','Лениградская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО Концерн Росэнергоатом Нововорнежская АЭС','Нововоронежская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО Концерн Росэнергоатом Нововоронежская атомная станция ','Нововоронежская Атомная Станция','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО Концерн Росэнергоатом Ростовская атомная станция','Ростовская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО НИКИМТ-Атомстрой Дирекция на Курской АЭС','НИКИМТ Атомстрой','',1);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО Русатом Инфраструктурные Решения в г. Глазове','Русатом Инфраструктурные решения','РИР',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АО Русатом инфраструктурные решения в городе Глазове ','Русатом Инфраструктурные решения','РИР',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал АОКонцерн Росэнергоатом Нововоронежская атомная станция','Нововоронежская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал Акционерного общества Научно-исследовательский и конструкторский институт монтажной технологии-Атомстрой Дирекция на Курской АЭС','','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал Акционерного общества Русатом Инфраструктурные решения в городе Новоуральске','Русатом Инфраструктурные решения','РИР',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал ОАО РЖД Свердловская дистанция гражданских сооружений','Русатом Инфраструктурные решения','РИР',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал ПАО Квадра- Курская генерация','Свердловская дистанция гражданских сооружений','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал ПАО Корпорация Иркут в г.Воронеж','Корпорация Иркут','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Филиал концерна Росэнергоатом Белоярская атомная электростанция','Белоярская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Химико-металлургический завод 20, Участок ремонта наружных электросетей и электрооборудования цехов','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Центр Компетенций WorldSkills Национального Исследовательского Ядерного Университета МИФИ','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Центральная научно-исследовательская лаборатория','НИЯУ МИФИ','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Центральное Конструкторское Бюро Машиностроения ','Центральное конструкторское бюро машиностроения','ЦКБМ',3);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Цех 90','Цех 90','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Цех сетей и подстанций','noteset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Цех тепловой автоматики и измерений','noteset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Цифровые платформы и решения для умного города','Цифровые платформы и решения Умного Города','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Частное учреждение Цифрум','Цифрум','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Чепецкий механический завод','Чепецкий механический завод','АО «ЧМЗ»',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Электрохимический завод','Производственное объединение «Электрохимический завод','ЭХЗ',2);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Электрохимприбор','Электрохимприбор, комбинат','',4);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('Южно-Уральский государственный университет (национальный исследовательский университет)','Южно-Уральский государственный университет (национальный исследовательский университет)','',6);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('котельный цех 006','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('нет данных','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('нижнетагильский металлургический комбинат ','notset','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('филиал АО Концерн Росэнергоатом Калининская АЭС','Калининская АЭС','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('филиал АО Концерн Росэнергоатом Нововоронежская атомная станция','Нововоронежская Атомная Станция','',5);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('филиал АО Концерн Росэнергоатом Опытно-демонстрационный инженерный центр по выводу из эксплуатации','Опытно-демонстрационный инженерный центр по выводу из эксплуатации','',13);
INSERT INTO workspace_correction(name, good_name, short_name, division_id) VALUES ('филиал АО НИКИМТ-Атомстрой','НИКИМТ Атомстрой','',1);